require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :rows, :ids, :noko, :counties
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:nv/
		end.reject do |line|
			line =~ /place:/
		end.map do |line|
			line.gsub(/,.+/, '').gsub(/\n/, '')
		end 
	end 

	def fetch_page

		arr_of_arrs = CSV.read("NevadaPage.csv").reject do |a|
			a.empty?
		end.map do |a|
			a[0] = a[0].downcase.split.map(&:capitalize).join(' ')
			a
		end.map do |a|
			a[1] = a[0].gsub(/( city)|( county)/i, "") + " " + a[1]
			a
		end.map do |a|
			name = a[0].gsub(/(county)|(city)/i, "").strip.gsub(" ", "_").gsub("'","~").gsub(".","")
			id = @ids.find do |i|	
				i =~ /#{name}/i
			end || ""
			a.push(id)
			a
		end.each do |a|
			@rows << a
		end

	end

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.fetch_page
a.write_into_CSV_file